### PR TITLE
added a suggestion

### PR DESCRIPTION
**Pull request by danishjuneja**

### CODE REVIEW

**Comment by priyansh32** [comment]
Great idea 👍🏼 I have already made two teams for web dev. I will make more. If you are interested in managing teams and organization, let me know 😄

**Comment by danishjuneja** [comment]
sure, @priyansh32, I could help in managing teams and organization

**Comment by priyansh32** [comment]
I have added you as owner. can you turn on Two Factor Auth, Github recommends owners to keep 2FA turned on.

**Comment by BenzeneAlcohol** [comment]
Let's open a data analytics team also
Anyone who is interested can join it (ping me).

**Comment by danishjuneja** [comment]
Yup, we can, @BenzeneAlcohol do you have any projects in mind?

**Pull request merged**
